---
- hosts: all
  become: true
  roles:
  - kazoo-ansible.common

- hosts: couchdb
  become: true
  roles:
  - kazoo-ansible.couchdb

- hosts: rabbitmq
  become: true
  roles:
  - kazoo-ansible.rabbitmq

- hosts: freeswitch
  become: true
  roles:
  - kazoo-ansible.freeswitch

- hosts: kamailio
  become: true
  roles:
  - kazoo-ansible.kamailio

- hosts: kazoo
  become: true
  roles:
  - kazoo-ansible.kazoo

- hosts: monsterui
  become: true
  roles:
  - kazoo-ansible.monsterui

- hosts: all
  become: true
  roles:
  - kazoo-ansible.updates

