---
- name: Set Public IP Facts
  publicip:

- name: Set System Time to UTC
  timezone:
    name: UTC

- name: Install 2600hz Stable Repo
  yum:
    name: https://packages.2600hz.com/centos/7/stable/2600hz-release/4.1/2600hz-release-4.1-0.el7.centos.noarch.rpm
    state: installed

- name: Install Delta RPMs
  yum:
    name: deltarpm
    state: latest

- name: Install Yum Utils
  yum:
    name: yum-utils
    state: latest

- name: Install Sup Python Library
  copy:
    src: library/sup.py
    dest: /usr/lib64/python2.7/sup.py

- name: Change FirewallD Default Zone to Public
  shell: firewall-cmd --set-default-zone=public
  changed_when: false
  check_mode: no

- name: Allow Kazoo nodes to communicate
  template:
    src: kazoo-zone.xml.j2
    dest: /etc/firewalld/zones/kazoo-zone.xml
  notify: Restart FirewallD

